import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
    en: {
        // General
        logout: 'Logout',
        yes: 'Yes',
        no: 'No',
        capture: 'Capture',
        access_portal: 'Access Portal',
        welcome_back: 'Welcome Back',
        sign_in_desc: 'Enter credentials to authorize session.',
        identity_access: 'Identity Access',
        security_shield: 'Security Shield',
        secure_login: 'SECURE LOGIN',
        management: 'MANAGEMENT',
        staff_portal: 'STAFF PORTAL',
        username_mobile: 'Username or Mobile',
        password_placeholder: '••••••••',
        current_profile: 'Current Profile',

        // Dashboard/Status
        noVehicle: 'No Vehicle Active',
        startDutyMessage: 'Please start your duty to select a vehicle.',
        assignedVehicle: 'YOUR ASSIGNED VEHICLE',
        punchIn: 'START DUTY',
        punchOut: 'END DUTY',
        dutyCompleted: 'Duty Completed',
        offDutyMessage: 'Your reports are submitted. You are now off-duty.',
        startNewDuty: 'Start New Duty',
        waitingAdmin: 'Waiting for Admin',
        reviewMessage: 'Your request is under review. Please wait.',
        total_drivers: 'Total Drivers',
        fleet_size: 'Fleet Size',
        concluded_duty: 'Concluded Duty',
        today: 'Today Duty',
        today_duty: 'Today Duty',
        personnel_hub: 'Personnel Hub',
        approvals: 'Approvals',
        onDuty: 'You are On Duty',
        driveSafely: 'Drive safely! Close duty only after reaching parking.',
        submitReports: 'Submit Reports & End Duty',

        // Punch In/Out Form
        dutyPunchIn: 'Start Duty',
        dutyPunchOut: 'End Duty',
        start: 'START',
        end: 'END',
        currentKm: 'CURRENT KM METER READING',
        enterKm: 'Enter KM',
        selectVehicle: 'Select Assigned Vehicle',
        selectCar: '-- Select Available Car --',
        driverSelfie: '1. DRIVER SELFIE',
        takeSelfie: 'Take Selfie',
        kmPhoto: '2. KM PHOTO',
        takeKmPhoto: 'Take KM Photo',
        carSelfie: '3. CAR SELFIE',
        takeCarPhoto: 'Take Car Photo',

        // Expenditure
        expenditureDetails: 'EXPENDITURE & TRIP DETAILS',
        refillNo: 'REFILL NO.',
        meterKm: 'Meter KM',
        captureSlip: 'Capture Slip',
        fuelType: 'Fuel Type',
        petrol: 'Petrol',
        diesel: 'Diesel',
        cng: 'CNG',
        electric: 'Electric',
        addAnotherBill: 'Add Another Bill',
        parkingQuestion: '2. Did you pay for parking?',
        receipt: 'Receipt',
        addAnotherParking: 'Add Another Parking',
        outsideCityQuestion: '3. Did you go outside city?',
        sameDay: 'SAME DAY',
        nightStay: 'NIGHT STAY',

        // Maintenance
        maintenanceIssues: 'DRIVER Service (OPTIONAL)',
        carWash: 'Car Wash',
        wash: 'Car Wash',
        lightIssue: 'Light Issue',
        puncture: 'Puncture',
        mechanical: 'Mechanical',
        accident: 'Accident/Dent',
        tissue: 'Tissue Box',
        waterBottle: 'Water Bottle',
        water: 'Water Bottle',
        other: 'Other',
        otherRemarks: 'Other Issues/Remarks',
        explainOptional: 'Explain (Optional)',
        remarksAdmin: 'REMARKS FOR ADMIN',
        enterRemarks: 'Enter remarks',
        submitPunchIn: 'Submit Punch-In',
        submitPunchOut: 'Submit Punch-Out',

        // Modals
        modalTakeSelfie: 'Take Selfie',
        modalCaptureKm: 'Capture KM Meter',
        modalTakeCarSelfie: 'Take Car Selfie',
        modalFuelSlip: 'Refill Slip Photo',
        modalParkingSlip: 'Parking Slip Photo',
        modalOtherSlip: 'Expense Slip Photo',
        modalCapturePhoto: 'Capture Photo',

        // Messages
        mandatoryFields: 'KM, Selfie, KM Photo, and Car Selfie are mandatory',
        fuelValidation: 'All fuel entries must have amount, KM and slip photo',
        parkingValidation: 'All parking entries must have amount and receipt',
        punchInSuccess: 'Successfully Punched In!',
        punchOutSuccess: 'Successfully Punched Out!',
        requestSent: 'Request sent to Admin. Awaiting approval.',
        requestFailed: 'Failed to send request',
        cameraError: 'Could not access camera. Please ensure you have given permission or are using HTTPS.',
        logExpense: 'Log Expense',
        addFuelParking: 'Add Fuel/Parking Slip',
        logFuel: 'Log Fuel',
        logParking: 'Log Parking',
        driverSeva: 'Driver Service',
        expenseSubmitted: 'Expense submitted for approval',
        approvalStatus: 'Approval Status',
        type: 'Expense Type',
        submit: 'Submit Log',
        processing: 'Processing...',
        noExpensesYet: 'No expenses added yet',

        // Ledger
        ledger: 'Salary & Duties',
        totalEarned: 'Total Earned',
        totalAdvance: 'Advance Taken',
        pendingAdvance: 'Advance Payment',
        netPayable: 'Net Payable',
        workingDays: 'Duties',
        downloadExcel: 'Download Report',
        downloadPDF: 'Download PDF Report',
        dutyHistory: 'Duty History',
        advanceHistory: 'Advance History',
        date: 'Date',
        vehicle: 'Vehicle',
        wage: 'Wage',
        bonus: 'Bonus',
        amount: 'Amount',
        quantity: 'Volume (L)',
        total: 'Total',
        specialPay: 'ADD. PAY (Special)',
        specialPayRemark: 'REMARK FOR SPECIAL PAY',
        specialPayoutHistory: 'SPECIAL PAYOUT (History)',
        volume_optional: 'Volume (L) - Optional',
        rate_per_l: 'Rate / L',
        charging_units: 'Units (kWh)',
        rate_per_kwh: 'Rate / kWh',

        // Admin Sidebar
        dashboard: 'Dashboard',
        ai_chatboard: 'AI ChatBoard',
        live_feed: 'Live Feed',
        log_book: 'Log Book',
        drivers_services: 'Drivers Services',
        drivers: 'Drivers',
        freelancers: 'Freelancers',
        parking: 'Parking',
        buy_sell: 'Buy/Sell',
        outside_cars: 'Outside Cars',
        event_management: 'Event Management',
        vehicles_life: 'Vehicles Life',
        maintenance: 'Maintenance',
        car_logs: 'Car Logs',
        vehicles_mgt: 'Vehicles MGT',
        active_logs: 'Active Logs',
        monthly_payroll: 'Monthly Payroll',

        fleet_operations: 'Fleet Operations',
        car_utility: 'Car Utility',
        fuel: 'Fuel',
        staff_management: 'Staff Management',
        manage_admins: 'Manage Admins',
        automotive_excellence: 'Automotive Excellence',
        admin_panel: 'Admin Panel',
        language: 'Language',
        english: 'English',
        hindi: 'Hindi',

        // Admin Dashboard
        fleet_control_center: 'Fleet Control Center',
        executive_dashboard: 'Executive Dashboard',
        total_driver_salary: 'TOTAL DRIVER SALARY',
        total_driver_advance: 'TOTAL DRIVER ADVANCE',
        fuel_monthly: 'FUEL (MONTHLY)',
        freelancers_monthly: 'FREELANCERS (MONTHLY)',
        outside_cars_monthly: 'OUTSIDE CARS (MONTHLY)',
        event_management_m: 'EVENT MANAGEMENT (M)',
        maintenance_monthly: 'MAINTENANCE (MONTHLY)',
        accident_cost_yearly: 'ACCIDENT COST (YEARLY)',
        parking_monthly: 'PARKING (MONTHLY)',
        fastag_recharge_monthly: 'FASTAG RECHARGE (MONTHLY)',
        driver_services_monthly: 'DRIVER SERVICES (MONTHLY)',

        fleet_size_label: 'FLEET SIZE',
        expiry_alerts: 'Expiry Alerts',
        overdue: 'Overdue',
        days_left_label: 'Left',
        today_label: 'Today',
        km_overdue: 'KM Overdue',
        km_due: 'KM Due',

        // Months
        month_1: 'January',
        month_2: 'February',
        month_3: 'March',
        month_4: 'April',
        month_5: 'May',
        month_6: 'June',
        month_7: 'July',
        month_8: 'August',
        month_9: 'September',
        month_10: 'October',
        month_11: 'November',
        month_12: 'December'
    },
    hi: {
        // General
        logout: 'लॉगआउट',
        yes: 'हाँ',
        no: 'नहीं',
        save: 'सहेजें',
        capture: 'फोटो लें',
        access_portal: 'एक्सेस पोर्टल',
        welcome_back: 'सुस्वागतम',
        sign_in_desc: 'सत्र अधिकृत करने के लिए क्रेडेंशियल दर्ज करें।',
        identity_access: 'पहचान एक्सेस',
        security_shield: 'सुरक्षा कवच',
        secure_login: 'सुरक्षित लॉगिन',
        management: 'प्रबंधन',
        staff_portal: 'स्टाफ पोर्टल',
        username_mobile: 'यूजरनेम या मोबाइल',
        password_placeholder: '••••••••',
        current_profile: 'वर्तमान प्रोफाइल',

        // Dashboard/Status
        noVehicle: 'कोई वाहन सक्रिय नहीं है',
        startDutyMessage: 'वाहन चुनने के लिए कृपया अपनी ड्यूटी शुरू करें।',
        assignedVehicle: 'आपका आवंटित वाहन',
        punchIn: 'पंच इन',
        punchOut: 'पंच आउट',
        dutyCompleted: 'ड्यूटी पूरी हुई',
        offDutyMessage: 'आपकी रिपोर्ट सबमिट हो गई है। अब आप ड्यूटी पर नहीं हैं।',
        startNewDuty: 'नई ड्यूटी शुरू करें',
        waitingAdmin: 'एडमिन का इंतज़ार है',
        reviewMessage: 'आपका अनुरोध विचाराधीन है। कृपया प्रतीक्षा करें।',
        total_drivers: 'कुल ड्राइवर',
        fleet_size: 'वाहन बेड़ा',
        concluded_duty: 'ड्यूटी समाप्त',
        today: 'आज की ड्यूटी',
        today_duty: 'आज की ड्यूटी',
        personnel_hub: 'कार्मिक हब',
        approvals: 'मंजूरी',
        onDuty: 'आप ड्यूटी पर हैं',
        driveSafely: 'सुरक्षित ड्राइव करें! पार्किंग स्थल पर पहुँचने के बाद ही ड्यूटी बंद करें।',
        submitReports: 'रिपोर्ट सबमिट करें और ड्यूटी समाप्त करें',

        // Admin Sidebar
        dashboard: 'डैशबोर्ड',
        ai_chatboard: 'AI चैटबोर्ड',
        live_feed: 'लाइव फीड',
        log_book: 'लॉग बुक',
        drivers_services: 'ड्राइवर सेवाएं',
        drivers: 'ड्राइवर',
        freelancers: 'फ्रीलांसर',
        parking: 'पार्किंग',
        buy_sell: 'खरीद/बिक्री',
        outside_cars: 'बाहरी गाड़ियाँ',
        event_management: 'इवेंट मैनेजमेंट',
        vehicles_life: 'वाहन जीवन',
        maintenance: 'रखरखाव',
        car_logs: 'गाड़ी लॉग',
        vehicles_mgt: 'वाहन प्रबंधन',
        active_logs: 'सक्रिय लॉग',
        monthly_payroll: 'मासिक पेरोल',

        fleet_operations: 'फ्लीट ऑपरेशंस',
        car_utility: 'कार उपयोगिता',
        fuel: 'ईंधन',
        staff_management: 'स्टाफ प्रबंधन',
        manage_admins: 'एडमिन प्रबंधित करें',
        automotive_excellence: 'ऑटोमोटिव उत्कृष्टता',
        admin_panel: 'एडमिन पैनल',
        language: 'भाषा',
        english: 'अंग्रेजी',
        hindi: 'हिंदी',

        // Admin Dashboard
        fleet_control_center: 'बेड़ा नियंत्रण केंद्र',
        executive_dashboard: 'कार्यकारी डैशबोर्ड',
        total_driver_salary: 'कुल ड्राइवर वेतन',
        total_driver_advance: 'कुल ड्राइवर एडवांस',
        fuel_monthly: 'ईंधन (मासिक)',
        freelancers_monthly: 'फ्रीलांसर (मासिक)',
        outside_cars_monthly: 'बाहरी गाड़ियाँ (मासिक)',
        event_management_m: 'इवेंट मैनेजमेंट (मासिक)',
        maintenance_monthly: 'रखरखाव (मासिक)',
        accident_cost_yearly: 'दुर्घटना लागत (वार्षिक)',
        parking_monthly: 'पार्किंग (मासिक)',
        fastag_recharge_monthly: 'फास्टैग रिचार्ज (मासिक)',
        driver_services_monthly: 'ड्राइवर सेवाएं (मासिक)',

        fleet_size_label: 'कुल गाड़ियाँ',
        expiry_alerts: 'समाप्ति अलर्ट',
        overdue: 'विलंबित',
        days_left_label: 'दिन शेष',
        today_label: 'आज',
        km_overdue: 'KM विलंबित',
        km_due: 'KM शेष',

        // Months
        month_1: 'जनवरी',
        month_2: 'फरवरी',
        month_3: 'मार्च',
        month_4: 'अप्रैल',
        month_5: 'मई',
        month_6: 'जून',
        month_7: 'जुलाई',
        month_8: 'अगस्त',
        month_9: 'सितंबर',
        month_10: 'अक्टूबर',
        month_11: 'नवंबर',
        month_12: 'दिसंबर',

        // Punch In/Out Form
        dutyPunchIn: 'ड्यूटी पंच-इन',
        dutyPunchOut: 'ड्यूटी पंच-आउट',
        start: 'शुरू',
        end: 'समाप्त',
        currentKm: 'वर्तमान KM मीटर रीडिंग',
        enterKm: 'KM दर्ज करें',
        selectVehicle: 'आवंटित वाहन चुनें',
        selectCar: '-- उपलब्ध गाड़ी चुनें --',
        driverSelfie: '1. ड्राइवर सेल्फी',
        takeSelfie: 'सेल्फी लें',
        kmPhoto: '2. KM फोटो',
        takeKmPhoto: 'KM फोटो लें',
        carSelfie: '3. गाड़ी की सेल्फी',
        takeCarPhoto: 'गाड़ी की फोटो लें',

        // Expenditure
        expenditureDetails: 'खर्च और यात्रा विवरण',
        fuelQuestion: '1. क्या आपने पेट्रोल/डीजल भरवाया?',
        refillNo: 'रीफिल नंबर',
        amountWithSymbol: 'राशि (₹)',
        meterKm: 'मीटर KM',
        captureSlip: 'रसीद की फोटो लें',
        fuelType: 'ईंधन का प्रकार',
        petrol: 'पेट्रोल',
        diesel: 'डीजल',
        cng: 'सीएनजी',
        electric: 'इलेक्ट्रिक',
        addAnotherBill: 'एक और बिल जोड़ें',
        parkingQuestion: '2. क्या आपने पार्किंग का भुगतान किया?',
        receipt: 'रसीद',
        addAnotherParking: 'एक और पार्किंग जोड़ें',
        outsideCityQuestion: '3. क्या आप शहर के बाहर गए थे?',
        sameDay: 'उसी दिन वापसी',
        nightStay: 'रात का ठहराव',

        // Maintenance
        maintenanceIssues: 'ड्राइवर सेवा (वैकल्पिक)',
        carWash: 'गाड़ी धुलाई',
        wash: 'गाड़ी धुलाई',
        lightIssue: 'लाइट की समस्या',
        puncture: 'पंचर',
        mechanical: 'मैकेनिकल',
        accident: 'दुर्घटना/डेंट',
        tissue: 'टिशू बॉक्स',
        waterBottle: 'पानी की बोतल',
        water: 'पानी की बोतल',
        other: 'अन्य',
        otherRemarks: 'अन्य मुद्दे/टिप्पणियां',
        explainOptional: 'समझाएं (वैकल्पिक)',
        remarksAdmin: 'एडमिन के लिए टिप्पणियां',
        enterRemarks: 'टिप्पणियां दर्ज करें',
        submitPunchIn: 'पंच-इन सबमिट करें',
        submitPunchOut: 'पंच-आउट सबमिट करें',

        // Modals
        modalTakeSelfie: 'सेल्फी लें',
        modalCaptureKm: 'KM मीटर कैप्चर करें',
        modalTakeCarSelfie: 'गाड़ी की सेल्फी लें',
        modalFuelSlip: 'ईंधन रसीद फोटो',
        modalParkingSlip: 'पार्किंग रसीद फोटो',
        modalOtherSlip: 'खर्च रसीद फोटो',
        modalCapturePhoto: 'फोटो कैप्चर करें',

        // Messages
        mandatoryFields: 'KM, सेल्फी, KM फोटो और गाड़ी की सेल्फी अनिवार्य हैं',
        fuelValidation: 'सभी ईंधन प्रविष्टियों में राशि, KM और रसीद फोटो होनी चाहिए',
        parkingValidation: 'सभी पार्किंग प्रविष्टियों में राशि और रसीद होनी चाहिए',
        punchInSuccess: 'सफलतापूर्वक पंच-इन हो गया!',
        punchOutSuccess: 'सफलतापूर्वक पंच-आउट हो गया!',
        requestSent: 'एडमिन को अनुरोध भेज दिया गया है। अनुमोदन की प्रतीक्षा है।',
        requestFailed: 'अनुरोध भेजने में विफल',
        cameraError: 'कैमरा एक्सेस नहीं किया जा सका। कृपया सुनिश्चित करें कि आपने अनुमति दी है या HTTPS का उपयोग कर रहे हैं।',
        logExpense: 'खर्च दर्ज करें',
        addFuelParking: 'ईंधन/पार्किंग रसीद जोड़ें',
        logFuel: 'ईंधन दर्ज करें',
        logParking: 'पार्किंग दर्ज करें',
        driverSeva: 'ड्राइवर सेवा',
        expenseSubmitted: 'खर्च अनुमोदन के लिए भेज दिया गया है',
        approvalStatus: 'अनुमोदन स्थिति',
        type: 'खर्च का प्रकार',
        submit: 'लॉग सबमिट करें',

        noExpensesYet: 'अभी तक कोई खर्च नहीं जोड़ा गया है',

        // Ledger
        ledger: 'सैलरी और ड्यूटी',
        totalEarned: 'कुल कमाई',
        totalAdvance: 'लिया गया एडवांस',
        pendingAdvance: 'एडवांस पेमेंट',
        netPayable: 'शुद्ध देय राशि',
        workingDays: 'कुल ड्यूटी',
        downloadExcel: 'रिपोर्ट डाउनलोड करें',
        downloadPDF: 'PDF रिपोर्ट डाउनलोड करें',
        dutyHistory: 'ड्यूटी का इतिहास',
        advanceHistory: 'एडवांस का इतिहास',
        date: 'तारीख',
        vehicle: 'गाड़ी',
        wage: 'वेतन',
        bonus: 'बोनस',
        amount: 'राशि',
        quantity: 'वॉल्यूम (L)',
        total: 'कुल',
        specialPay: 'अतिरिक्त भुगतान (स्पेशल)',
        specialPayRemark: 'स्पेशल पे के लिए टिप्पणी',
        specialPayoutHistory: 'स्पेशल पेआउट (इतिहास)',
        volume_optional: 'वॉल्यूम (L) - वैकल्पिक',
        rate_per_l: 'रेट',
        charging_units: 'यूनिट्स (kWh)',
        rate_per_kwh: 'रेट / kWh',
        payment_source: 'भुगतान का स्रोत',
        office: 'ऑफिस',
        guest: 'गेस्ट',
        optional: 'वैकल्पिक'
    }
};

// export const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(localStorage.getItem('language') || 'en');

    useEffect(() => {
        localStorage.setItem('language', language);
    }, [language]);

    const t = (key) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
